#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if LC_ALL=C dpkg --compare-versions "$2" lt-nl "1.0.8-3pexip2~"; then
        # No longer wanted by basic.target: clean up on upgrade
        deb-systemd-helper reenable jitterentropy.service >/dev/null || true
        rmdir --ignore-fail-on-non-empty /etc/systemd/system/basic.target.wants
        rmdir --ignore-fail-on-non-empty /var/lib/systemd/deb-systemd-helper-enabled/basic.target.wants
    fi
fi

#DEBHELPER#
